//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace bla
{
    using System;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "GeoIPServiceSoap12", Namespace = "http://www.webservicex.net/")]
    public partial class GeoIPService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        /// <remarks/>
        public GeoIPService()
        {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = "http://www.webservicex.net/geoipservice.asmx";
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webservicex.net/GetGeoIP", RequestNamespace = "http://www.webservicex.net/", ResponseNamespace = "http://www.webservicex.net/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GeoIP GetGeoIP(string IPAddress)
        {
            object[] results = this.Invoke("GetGeoIP", new object[] {
                    IPAddress});
            return ((GeoIP)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webservicex.net/GetGeoIPContext", RequestNamespace = "http://www.webservicex.net/", ResponseNamespace = "http://www.webservicex.net/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GeoIP GetGeoIPContext()
        {
            object[] results = this.Invoke("GetGeoIPContext", new object[0]);
            return ((GeoIP)(results[0]));
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.webservicex.net/")]
    public partial class GeoIP : object, System.ComponentModel.INotifyPropertyChanged
    {

        /// <remarks/>
        public int ReturnCode;

        /// <remarks/>
        public string IP;

        /// <remarks/>
        public string ReturnCodeDetails;

        /// <remarks/>
        public string CountryName;

        /// <remarks/>
        public string CountryCode;

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}